#!/usr/bin/env bash
#Bash script that will display information about subdomains.

display_subdomain() {
	subdomain="$1"
	domain="$2"

	dig_output=$(dig "$subdomain.$domain" | grep -A1 'ANSWER SECTION:')

	record_type=$(echo "$dig_output" | awk 'NR==2 {print $4}')
	destination=$(echo "$dig_output" | awk 'NR==2 {print $5}')

	echo "The subdomain $subdomain is a $record_type record and points to $destination"
}

display_all_subdomain() {
	display_subdomain "www" "$1"
	display_subdomain "lb-01" "$1"
	display_subdomain "web-01" "$1"
	display_subdomain "web-02" "$1"
}

if [ "$#" -eq 1 ]; then
    # If only domain is provided, display information for all subdomains
    display_all_subdomain "$1"
elif [ "$#" -eq 2 ]; then
    # If both domain and subdomain are provided, display information for the specified subdomain
    display_subdomain "$2" "$1"
else
    echo "Usage: $0 <domain> [subdomain]"
    exit 1
fi
