#!/usr/bin/env bash
# A script to Install nginx on your web-01
# Nginx should be listening on port 80
# When querying Nginx at its root / with a GET request (requesting a page)
# using curl, it must return a page that contains the string Hello World!

apt-get update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.nginx-debian.html
echo "Ceci n'est pas une page" > 404_error.html
mv 404_error.html /var/www/html/

sed -i '/listen 80 default_server/a error_page 404 /404_error.html;\n\tlocation = /404_error.html {\n\t\troot /var/www/html;\n\t}' /etc/nginx/sites-available/default

if [ "$(pgrep -c nginx)" -le 0 ]; then
	service nginx start
else
	service nginx restart
fi
