#!/usr/bin/env bash
# Configuring webserver
# Installs a Nginx server

sudo apt-get -y update
sudo apt-get -y install nginx
sudo echo "Hello World!" > /var/www/html/index.nginx-debian.html
echo "Ceci n'est pas une page" > 404_error.html
sudo mv 404_error.html /var/www/html/

sudo sed -i '/listen 80 default_server/a error_page 404 /404_error.html;\n\tlocation = /404_error.html {\n\t\troot /var/www/html;\n\t}' /etc/nginx/sites-available/default
sudo sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://www.github.com/eael permanent;' /etc/nginx/sites-available/default

if [ "$(pgrep -c nginx)" -le 0 ]; then
	service nginx start
else
	service nginx restart
fi
