#!/usr/bin/env bash
# Configuring webserver
# Installs a Nginx server
# sets up error page and header
sudo apt-get -y update
sudo apt-get -y install nginx
sudo echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo echo "Ceci n'est pas une page" > /usr/share/nginx/html/404_error.html
sudo sed -i "s/server_name _;/server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/eael permanent;\n\n\terror_page 404 \/404_error.html;\n\tlocation = \/404_error.html {\n\t\troot \/usr\/share\/nginx\/html;\n\t\tinternal;\n\t}/" /etc/nginx/sites-available/default

sudo sed -i "s/include \/etc\/nginx\/sites-enabled\/\*;/include \/etc\/nginx\/sites-enabled\/\*;\n\tadd_header X-Served-By \"$HOSTNAME\";/" /etc/nginx/nginx.conf

sudo service nginx start
