#!/usr/bin/env bash
# Installs and setup haproxy

sudo apt-get update
sudo apt-get -y install --no-install-recommends software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.4
sudo apt-get -y install haproxy

sudo echo ENABLED=1 > /etc/default/haproxy

# Listen to web1 and web2 server

sudo echo "
   listen load_balancer
   bind *:80
   mode http
   balance roundrobin
   option httpclose
   option forwardfor
   server 225943-web-01 54.237.227.47:80 check
   server 225943-web-02 100.26.233.49:80 check
" >> /etc/haproxy/haproxy.cfg

sudo service haproxy start
