#!/usr/bin/env bash
# This script is displaying "Best School" 10 times using while loop
# If the iteration is 4, display bad luck
# else if the iteration is 8, display good luck
i=1
while ((i<=10))
do
	msg="Best School"
	if ((i == 4)); then
		echo "bad luck"
	elif ((i == 8)); then
		echo "good luck"
	else
		echo "$msg"
	fi
	((i++))
done
