#!/usr/bin/env bash
# This script is displaying numbers from a clock
# From hour: 0 to 12 and minutes: 1 to 59
h=0
while (("$h" < 13))
do
	echo "Hour: $h"
	m=1
	while (("$m" < 60))
	do
		echo "$m"
		((m++))
	done
	((h++))
done
