#!/usr/bin/env bash
# A script for changing the etc/hosts file

# Make backup of original file
cp /etc/hosts /etc/hosts.old

cp /etc/hosts ~/hosts.new
echo "127.0.0.2	localhost" > ~/hosts.new
echo "8.8.8.8	facebook.com" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
