#!/usr/bin/env bash
# Lets a server run Nginx as the nginx user listening on 8080

sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
chmod 700 /etc/nginx/nginx.conf
pkill apache2
sudo -u nginx service nginx start
